version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    env_file:
      - ../.env

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lets_go
    ports:
      - "5432:5432"

volumes:
  postgres-data:
