# Thanks to ChatGPT for the launchpad: https://chatgpt.com/share/67b829fa-86fc-8013-9500-86e6853ffdeb
name: Go CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4

      - name: Install dependencies
        run: go mod download
        working-directory: ./backend

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        run: ~/go/bin/golangci-lint run
        working-directory: ./backend

      - name: Build
        run: go build -v ./...
        working-directory: ./backend

      - name: Test
        run: go test -v ./...
        working-directory: ./backend
